# Generated by Django 4.2.1 on 2023-06-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='logo',
        ),
    ]
